/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XsuchyAmbulance {
    }
    interface XsuchyAmbulanceEditor {
    }
}
declare global {
    interface HTMLXsuchyAmbulanceElement extends Components.XsuchyAmbulance, HTMLStencilElement {
    }
    var HTMLXsuchyAmbulanceElement: {
        prototype: HTMLXsuchyAmbulanceElement;
        new (): HTMLXsuchyAmbulanceElement;
    };
    interface HTMLXsuchyAmbulanceEditorElement extends Components.XsuchyAmbulanceEditor, HTMLStencilElement {
    }
    var HTMLXsuchyAmbulanceEditorElement: {
        prototype: HTMLXsuchyAmbulanceEditorElement;
        new (): HTMLXsuchyAmbulanceEditorElement;
    };
    interface HTMLElementTagNameMap {
        "xsuchy-ambulance": HTMLXsuchyAmbulanceElement;
        "xsuchy-ambulance-editor": HTMLXsuchyAmbulanceEditorElement;
    }
}
declare namespace LocalJSX {
    interface XsuchyAmbulance {
    }
    interface XsuchyAmbulanceEditor {
    }
    interface IntrinsicElements {
        "xsuchy-ambulance": XsuchyAmbulance;
        "xsuchy-ambulance-editor": XsuchyAmbulanceEditor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xsuchy-ambulance": LocalJSX.XsuchyAmbulance & JSXBase.HTMLAttributes<HTMLXsuchyAmbulanceElement>;
            "xsuchy-ambulance-editor": LocalJSX.XsuchyAmbulanceEditor & JSXBase.HTMLAttributes<HTMLXsuchyAmbulanceEditorElement>;
        }
    }
}
