/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XsuchyAmbulancePresuny {
    }
}
declare global {
    interface HTMLXsuchyAmbulancePresunyElement extends Components.XsuchyAmbulancePresuny, HTMLStencilElement {
    }
    var HTMLXsuchyAmbulancePresunyElement: {
        prototype: HTMLXsuchyAmbulancePresunyElement;
        new (): HTMLXsuchyAmbulancePresunyElement;
    };
    interface HTMLElementTagNameMap {
        "xsuchy-ambulance-presuny": HTMLXsuchyAmbulancePresunyElement;
    }
}
declare namespace LocalJSX {
    interface XsuchyAmbulancePresuny {
    }
    interface IntrinsicElements {
        "xsuchy-ambulance-presuny": XsuchyAmbulancePresuny;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xsuchy-ambulance-presuny": LocalJSX.XsuchyAmbulancePresuny & JSXBase.HTMLAttributes<HTMLXsuchyAmbulancePresunyElement>;
        }
    }
}
